# Foundry Configuration for Credit CDP Protocol
# London EVM Compatible (CreditCoin Testnet)

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

# Solidity compiler settings
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 200
via_ir = false

# IMPORTANT: London EVM compatibility
# Do NOT use: paris, shanghai, cancun, or later
evm_version = "london"

# Testing
fuzz_runs = 256
ffi = false

# Additional settings
auto_detect_solc = false
gas_reports = ["*"]
verbosity = 2

[profile.ci]
fuzz_runs = 5000
verbosity = 4

[rpc_endpoints]
creditcoin_testnet = "${RPC_URL}"

[etherscan]
creditcoin_testnet = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_API_URL}" }

# Formatter settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
