export const VaultManagerABI = [
  {
    type: 'function',
    name: 'openVault',
    inputs: [
      { name: 'collateralAmount', type: 'uint256' },
      { name: 'debtAmount', type: 'uint256' },
      { name: 'interestRate', type: 'uint256' },
    ],
    outputs: [{ name: 'vaultId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'openVaultNative',
    inputs: [
      { name: 'debtAmount', type: 'uint256' },
      { name: 'interestRate', type: 'uint256' },
    ],
    outputs: [{ name: 'vaultId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'openVault',
    inputs: [
      { name: 'collateralAmount', type: 'uint256' },
      { name: 'debtAmount', type: 'uint256' },
    ],
    outputs: [{ name: 'vaultId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'adjustVault',
    inputs: [
      { name: 'vaultId', type: 'uint256' },
      { name: 'collateralDelta', type: 'int256' },
      { name: 'debtDelta', type: 'int256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'depositCollateralNative',
    inputs: [
      { name: 'vaultId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdrawCollateralNative',
    inputs: [
      { name: 'vaultId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'closeVault',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'closeVaultNative',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeem',
    inputs: [
      { name: 'rUSDAmount', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    outputs: [{ name: 'collateralRedeemed', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeemNative',
    inputs: [
      { name: 'rUSDAmount', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    outputs: [{ name: 'collateralRedeemedNative', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeemWithCap',
    inputs: [
      { name: 'rUSDAmount', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'maxInterestRate', type: 'uint256' },
    ],
    outputs: [{ name: 'collateralRedeemed', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeemAdvanced',
    inputs: [
      { name: 'rUSDAmount', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'maxInterestRate', type: 'uint256' },
      { name: 'preferLargerDebt', type: 'bool' },
    ],
    outputs: [{ name: 'collateralRedeemed', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getVaultBasic',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'collateral', type: 'uint256' },
      { name: 'debt', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVaultInterest',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [{ name: 'interest', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updateInterestRate',
    inputs: [
      { name: 'vaultId', type: 'uint256' },
      { name: 'newRate', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getUserVaults',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: 'vaultIds', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVaultCollateralRatio',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [{ name: 'ratio', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'canLiquidate',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRedeemableAmount',
    inputs: [{ name: 'rUSDAmount', type: 'uint256' }],
    outputs: [{ name: 'estimatedCollateral', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRedemptionFee',
    inputs: [{ name: 'collateralAmount', type: 'uint256' }],
    outputs: [{ name: 'fee', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minCollateralRatio',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'borrowingFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'redemptionFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalDebt',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalCollateral',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTotalDebtCurrent',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getInterestStats',
    inputs: [],
    outputs: [
      { name: 'minRate', type: 'uint256' },
      { name: 'maxRate', type: 'uint256' },
      { name: 'avgRate', type: 'uint256' },
      { name: 'weightedAvgRate', type: 'uint256' },
      { name: 'count', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'VaultOpened',
    inputs: [
      { name: 'vaultId', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'collateralAmount', type: 'uint256', indexed: false },
      { name: 'debtAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RedemptionExecuted',
    inputs: [
      { name: 'redeemer', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'rUSDAmount', type: 'uint256', indexed: false },
      { name: 'wCTCReceived', type: 'uint256', indexed: false },
      { name: 'feeAmount', type: 'uint256', indexed: false },
    ],
  },
] as const;
